### ISSUE TITLE
Wrong "default" package name in the displayed web action endpoints

### ISSUE THREAD

**Issue by cjelger** [serverless/serverless-openwhisk#105]
If an action is deployed in a specific package (other than the "default" package), the output of `serverless info` shows a wrong URL for the action as it wrongly adds the `default` package name.

Example output:
```
endpoints (web actions):
https://192.168.33.16/api/v1/web/my-namespace/my-package/default/helloworld
```

There shouldn't be any "default" string in the URL.

It seems the error comes from https://github.com/serverless/serverless-openwhisk/blob/master/info/index.js#L89 where "default" can simply be replaced with `${action.package}`?

Funny though that it properly displays the correct package ... is this "embedded" into `${action.namespace}`?

**Comment by jthomas** [comment]
Thanks for finding this, should be simple to fix. 

You are correct that the package is included in the `action.namespace` field rather than the `action.name` 🤷‍♂️
