### ISSUE TITLE
Version compatibility issues?

### ISSUE THREAD

**Issue by nerdguru** [serverless/serverless-openwhisk#117]
I'm revisiting the plugin after being away for 6 months or so and while I can create a new template, the deployment is failing claiming the plug-in isn't installed when it is:

$ serverless create --template openwhisk-nodejs --path my_service
Serverless: Generating boilerplate...
Serverless: Generating boilerplate in "/Users/petercjo/owtewt/my_service"
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.27.2
 -------'

Serverless: Successfully generated boilerplate for template: "openwhisk-nodejs"
$ cd my_service/
$ serverless deploy
 
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-openwhisk" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.14.2
     Serverless Version:     1.27.2

I've got an OpenWhisk VM set up on AWS that I can use the wsk CLI to interact with within that VM, even using the public IP address of the VM.  I copied/pasted the .wskprops I'm successfully using there to my local machine, which the plugin should be using.  Passing the -v switch into the serverless command doesn't reveal anything additional.

Might I have some version conflicts here or do you have any other troubleshooting suggestions?

**Comment by rupakg** [comment]
@nerdguru try `npm install` on your project folder and see if it fixes it.

**Comment by nerdguru** [comment]
I've got some larger network thing going on I didn't realize.  Sorry to bother you guys.  If I can eliminate that and still run into this I'll repopen

**Comment by rupakg** [comment]
@nerdguru you know it is not a bother. feel free to reach out. you know where to find me ;)
