### ISSUE TITLE
Fully automatic webpack support

### ISSUE THREAD

**Issue by alexkli** [serverless/serverless-openwhisk#118]
## Problem

There is a [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) plugin, but it requires manual work for things that could be automatic for an OpenWhisk NodeJS runtime environment:

* must provide and configure `webpack.config.js` - now you have at least 3 required files for build/deployment with `package.json` &`serverless.yml`, taking away from the simplicity of serverless just being one script
* must manually configure webpack `externals` for the node modules preinstalled on the openwhisk nodejs6 etc. runtimes to optimize the action size (webpack's tree shaking helps, but if your action limit is 1 MB that's easy to hit with huge libraries like `aws-sdk` that can be on the container)

## Proposal

* Generate the `webpack.config.js` automatically _iff_ serverless-webpack plugin is present (enabled in `serverless.yml`) and no custom `webpack.config.js` already exists
* Allow to pass webpack's `mode` as command line option to `serverless deploy` or `package`, which is either `production` (minimized & obfuscated) or `development` (keep full sources for debugging).
* Automatically exclude preinstalled node modules present on the docker image via webpack's `externals`. This can happen by
   * including such list files in the plugin itself for standard openwhisk containers, determined by `runtime`, fully automatic, or
   * referencing custom files that list these for customized containers but from a shared place, based on `runtime` and `image`.

  How these files are managed and referenced is still an open question.
* Any future additional config options (if needed) can be added inside `serverless.yml` and/or as cli options and passed through to the automatically generated `webpack.config.js`

## State

I have a working prototype and would be ready to release this as separate plugin, but I think it would work nice as part of the serverless-openwhisk plugin.

**Comment by jthomas** [comment]
Thanks for the detailed feedback, I can understand the issue you have encountered.

This would be a useful extension for developers but looks more like an external plugin than something that should be in the core?

If we merged this into the core, it would mean a larger provider plugin for all users (not just those using node.js and webpack). 

Have you considering talking to the `webpack` module owner to see if some of those changes can be created upstream? Some of the features seem provider-agonstic, rather than OW specific. If that happens, then you may be able to do an even smaller openwhisk-specific webpack plugin on top.

**Comment by alexkli** [comment]
I do want to avoid that a user has to add tons of plugins to their `serverless.yml` and install all of them via npm, if possible. The main point I am trying to solve is to simplify the dev process.

The `serverless-webpack` plugin would make sense in that regard. I filed an issue at https://github.com/serverless-heaven/serverless-webpack/issues/399 let's see what they think.

**Comment by jthomas** [comment]
Closing this ticket for the time being due to lack of activity.
