### ISSUE TITLE
Ruby runtime support

### ISSUE THREAD

**Issue by DamirSvrtan** [serverless/serverless-openwhisk#144]
Hello there! 👋 

First of all, thank you for your work on this project!

I see that 15 days ago the Ruby runtime support was added to the repository, however it is not included in the latest release of the plugin (that happened 25 days ago).

Do you know when the new version is going to be released?

**Comment by jthomas** [comment]
@DamirSvrtan Hello! I'm hoping to get this realised this week. During developent, I found an issue with Ruby support in OpenWhisk that I need to fix first (https://github.com/apache/incubator-openwhisk-runtime-ruby/pull/15).

**Comment by jthomas** [comment]
This is now available in 0.16!
