### ISSUE TITLE
Instructions incorrect with new authentication model of whisk service

### ISSUE THREAD

**Issue by dpittner** [serverless/serverless-openwhisk#18]
Setting up the cli according to the document doesn't work when following the current CLI instructions that are linked:
https://console.ng.bluemix.net/openwhisk/cli

The rules fail to deploy unless I'm explicitly setting a namespace in .wskprops. (Which is not what the CLI suggests)

Error is:
Serverless: Packaging service...
Serverless: Compiling Functions...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiling Triggers & Feeds...
Serverless: Deploying Functions...
Serverless: Deploying Triggers...
Serverless: Deploying Rules...
 
  Serverless Error ---------------------------------------
 
     Failed to deploy rule (my_service_event_name_to_hello_world)
     due to error: OpenWhisk authentication failed, check
     API key? The supplied authentication is not authorized
     to access this resource.
 
  Stack Trace --------------------------------------------
 
ServerlessError: Failed to deploy rule (my_service_event_name_to_hello_world) due to error: OpenWhisk authentication failed, check API key? The supplied authentication is not authorized to access this resource.
    at disableRule.then.catch.err (/home/dpittner/whisk/serverless-openwhisk-boilerplate/node_modules/serverless-openwhisk/deploy/lib/deployRules.js:9:15)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.3.0
     Serverless Version: 1.4.0

**Comment by dpittner** [comment]
When thinking about this more, this is more likely a problem with wsk-cli

**Comment by dpittner** [comment]
I think this will work once https://github.com/openwhisk/openwhisk/issues/1673 has been fixed.

**Comment by jthomas** [comment]
Thanks for reporting this, I'll look into it.

**Comment by jthomas** [comment]
Should be resolved with the latest commit.
