### ISSUE TITLE
Remove default implicit configuration that sets the concurrency to 1

### ISSUE THREAD

**Issue by cjelger** [serverless/serverless-openwhisk#183]
If the concurrency of an action is not configured, the plugin sets it to 1 by default, because of https://github.com/serverless/serverless-openwhisk/blob/1de03125ab7bcbf2d27d5a3ab2eb17f9b53500b6/compile/functions/index.js#L58

This is a problem because it overrides the default concurrency that can be set by default on the Openwhisk platform itself. So for example, if the platform defines a default concurrency of 200, not setting it in the `serverless` config "silently" resets this to 1.

I'll provide a PR for that.

**Comment by cjelger** [comment]
@jthomas I'm wondering if we also want to the same removal of the default values for the `memory` and `timeout` parameters. WDYT?

**Comment by cjelger** [comment]
@jthomas Gentle ping wrt. the previous comment, thanks.

**Comment by jthomas** [comment]
@cjelger +1 that's good idea.
