### ISSUE TITLE
serverless deploy results in syntax error due to strict mode not being supported

### ISSUE THREAD

**Issue by nauerz-ibm** [serverless/serverless-openwhisk#33]
$ serverless deploy
 
  Syntax Error -------------------------------------------
 
     Block-scoped declarations (let, const, function, class)
     not yet supported outside strict mode
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       5.6.0
     Serverless Version: 1.6.1

**Comment by jthomas** [comment]
I've added an "engines" flag to the package.json to enforce the requirement that the plugin relies on the Node.js 6.X or above. 

This has been highlighted in the README as a requirement.
