### ISSUE TITLE
API management

### ISSUE THREAD

**Issue by nieleyde** [serverless/serverless-openwhisk#35]
Could you provide more details on the API mgmt implementation?  From the endpoint URL I'm assuming that Bluemix IBM API Connect is being used, however I don't see the API connect service provisioned under my Bluemix account.  Is some other instance of the service being used?  How can I use my provisioned instance API Connect in Bluemix?

Thanks in advance.

**Comment by jthomas** [comment]
Hello @nieleyde 

API management is handled using the experimental API gateway feature:
https://github.com/openwhisk/openwhisk/blob/master/docs/apigateway.md

The API gateway used will be dependent on the OpenWhisk provider's implementation. I'm not sure what happens on IBM Bluemix, I'll ask a colleague to let you know.

**Comment by csantanapr** [comment]
Hi @nieleyde currently in Bluemix API Connect service is not being used.
What's being used in Bluemix is what @jthomas mentioned a cluster of instance of the containerhttps://github.com/openwhisk/openwhisk-apigateway

**Comment by nieleyde** [comment]
Thanks for the info.
