### ISSUE TITLE
Add ignore_certs constructor option (or make it available)

### ISSUE THREAD

**Issue by avwsolutions** [serverless/serverless-openwhisk#36]
Add ignore_certs constructor option (or make it available) like wsk -i). Currently I get an error during deploy of the boilerplate.

Failed to deploy function (localess-dev-hello_world)
 due to error: Error encountered calling OpenWhisk: Error:
 self signed certificate

**Comment by jthomas** [comment]
Thanks for reporting this. I will add this in.

**Comment by avwsolutions** [comment]
HI James,
Thanks it would be great. I already found some other engineers reporting the same issue at the Serverless forum](http://forum.serverless.com). I will communicate this coming fix within the forum. If you need some testing you can contact me.

**Comment by jthomas** [comment]
Thanks for the heads-up, I hadn't been monitoring the forum.

**Comment by jthomas** [comment]
@avwsolutions I've added the code for this, it'll be released in the upcoming 0.5 version. 

I'll close this ticket when it's available.
