### ISSUE TITLE
Handle returned error code differently based on the serverless command

### ISSUE THREAD

**Issue by cjelger** [serverless/serverless-openwhisk#50]
In the case where, for example, the API gateway functionality is disabled, calling `serverless deploy` fails when the command tries to get the api-gw endpoints. The command also returns an error code to the Linux shell, so any automated deployment script (for example in Jenkins) considers the deployment to have failed. However, the deployment succeeded, what failed was the call to display  the summary info printed to the standard output.

The command should maybe only abort and return an error code if the "main" `serverless`command failed. For example, `serverless deploy` should only fail when the deployment failed, while `serverless info` should fail if getting the api-gw endpoints has failed.

In the case where `serverless deploy` works but getting the api-gw info fails, this should still be displayed in the output of the command, the only difference should be that the command does not abort and does not return an error code to the Linux shell.

**Comment by jthomas** [comment]
Thanks for the PR, I've merged this. Will be included in the upcoming release.

**Comment by cjelger** [comment]
Ok thx!
