### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by shikhirsingh** [serverless/serverless-openwhisk#52]
There needs to be support for CORS in serverless.yaml, similar to that provided by AWS

**Comment by jthomas** [comment]
Thanks for the feedback, I'd add this feature when I'm updating the API GW service to use the new production service. 

https://github.com/serverless/serverless-openwhisk/issues/53

**Comment by jthomas** [comment]
Hello @shikhirsingh. 

I've been investigating this and the short answer is I won't be able to include this feature for the upcoming release (0.7). 

With the new [API Gateway support](https://github.com/serverless/serverless-openwhisk/issues/53), CORS is turned on by default for all APIs with the following headers. You do not need to configure this manually. 
```
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
Access-Control-Allow-Origin: *
```

I want to provide support for turning it off and (if possible) controlling the header values as you can do with AWS Lambda + API Gateway. Looking into the code on how to do this, it's not simple and I'll need to spend more time understanding the APIs before I can get this ready. As I want to get the 0.7 release out this week, I'll have to move this feature back to a later release. 

Thanks for opening this issue and giving me feedback, I'll plan to work on this for the 0.8 release.

**Comment by shikhirsingh** [comment]
@jthomas Did you get a chance to implement in 0.8?

**Comment by jthomas** [comment]
@shikhirsingh Hey, I have not. I haven't had much time to work on the project recently. It might might be a few months before I get round to adding this. I would happily accept a PR if you want to work on it?

**Comment by shikhirsingh** [comment]
Any workaround? This is a significant deficiency for those creating single page apps.

**Comment by jthomas** [comment]
@shikhirsingh CORS is enabled by default for APIs, are you saying you want to turn it off or that you want more control over the CORS options returned?

**Comment by jthomas** [comment]
CORS is on by default - this can now be turned off using configuration.
