### ISSUE TITLE
Add support for bluemix credentials from file.

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#57]
Bluemix CLI stores credentials in the user's home directory under `.cf` folder. This will be a better place to automatically pull credentials from rather than `.wsk`. 

This will include new API Gateway tokens that are required for OpenWhisk on Bluemix.

**Comment by sroze** [comment]
> This will include new API Gateway tokens that are required for OpenWhisk on Bluemix.

I think that this especially should be documented 👍

**Comment by jthomas** [comment]
Closing this issue as it's now out of date as the IBM Cloud CLI has changed significantly.
