### ISSUE TITLE
APIGW Response Content Type + Raw Web Action

### ISSUE THREAD

**Issue by bbilger** [serverless/serverless-openwhisk#59]
Hi,
I am rather new to openwhisk, so I hope the statements here are correct and please correct me if I am wrong!

Is there any way to set the response content type for an API Gateway endpoint? To me it looks as if the response content type is automatically set to `application/json`. It would be helpful if we were able to set it to `http` (`Use "Content-Type" header from action`) or any of the possible values (see below). This  would allow us to return a "http" response from the web action:
```
{
  statusCode: 200,
  body: ...,
  headers: ...
}
```
In addition: 
Since the API Gateway is just a proxy to web actions and invoking an endpoint triggers the web action, it would be helpful if we were able to flag the created web action as "raw" (https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#raw-http-handling). This would allow us to get the raw query string and request body.

--
The response content type I was talking about above...
![response_content_type](https://user-images.githubusercontent.com/6827090/26948931-627a1964-4c98-11e7-8939-95679295d259.png)

**Comment by jthomas** [comment]
Thanks for the feedback. I'll investigate and see how easy this would be to do do for the next release.

**Comment by maxfrigge** [comment]
There is also another response type `http`, which supports body, headers and status. 

https://github.com/apache/incubator-openwhisk/blob/master/docs/apigateway.md#full-control-over-the-http-response

**Comment by jthomas** [comment]
This issue is the same as raised here:
https://github.com/serverless/serverless-openwhisk/issues/80

I've now created a fix and will release in a few days.
