### ISSUE TITLE
Add internal hookable lifecycle events for the OpenWhisk plugin to the cheat sheet

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless-openwhisk#63]
Does the plugin add any internal lifecycle events (similar to the extensions, the AWS plugin does)?

If yes, then it would be great if I could add them to the **Plugin author's lifecycle cheat sheet** available here https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406. Currently the GIST doc only shows the aws specific sub lifecycles, but as it is intended to be provider independent it would be great to add the other provider's hookable events too.

BTW: I keep the document consistent with any lifecycle changes in the core framework already.

**Comment by jthomas** [comment]
Hello 👋.

Not at the moment, I didn't know provider plugins could expose events until now! 

I need to have a look over the code and check if there's anything it would make sense to expose.

**Comment by HyperBrain** [comment]
Yeah. It offers great improvements for other plugin writers that want (or must) offer different behavior for provider agnostic or specific plugins.
