### ISSUE TITLE
How to create APIGW --response-type http with Serverless

### ISSUE THREAD

**Issue by allansduarte** [serverless/serverless-openwhisk#80]
Hi there!

I am looking for guidelines for creating apigw that responds to the content-type header.

Whenever I create an API via Serverless it seems that the content-type is always JSON, I'm looking for a `'content-type': 'text/html'`.

That works like this:

Payload:
```
return {
   headers: {
     'content-type': 'text/html'
   },
   body: '123456',
     statusCode: 200
   };
```
Output:
`123456`

_It works perfectly when creating with wsk CLI, but with serverless no._

**Comment by jthomas** [comment]
Looking into this issue, the serverless framework plugin needs to pass the correct parameter during route creation to enable this. I'll need to update the `openwhisk-client-js` library to support this and also then implement this in the framework.

**Comment by jthomas** [comment]
I've pushed a fix for this to master and will release in a few days.

https://github.com/serverless/serverless-openwhisk#connecting-http-endpoints

**Comment by allansduarte** [comment]
Thanks @jthomas this feature will be very important for everyone who uses Serverless Openwhisk. The deployment flow remains continuous using Serverless.

I do not know if it is the best way, but in the meantime I found a temporary solution that worked here and that can be used for those who have the same question:

In serverless.yml has been disabled `http events` and enabled `annotations` to create an action with `web true`.
```yml
service: chatbot
...
   getWebhook:
     handler: dist/handler.sampleWebhook
     annotations:
       web-export: true
# events:
# - http: GET /bot /webhook
```

After this you create an APIGW manually:
```cli
wsk api create /chatbot /bot/webhook get chatbot-dev-sampleWebhook --response-type http
```
