### ISSUE TITLE
initialization errored: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by dbachko** [serverless/serverless-openwhisk#90]
Can't deploy function, I'm getting this error:

`Serverless plugin "serverless-openwhisk" initialization errored: Cannot find module 'lodash'`

<img width="749" alt="screen shot 2017-11-15 at 2 39 10 pm" src="https://user-images.githubusercontent.com/9260214/32856447-df5a4254-ca12-11e7-838b-a8dfcf0ca073.png">

**Comment by maxfrigge** [comment]
@jthomas would you mind publishing a new version to NPM with this fix included?
