### ISSUE TITLE
Allow Creation of Packages and Define Parameters

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless-openwhisk#96]
When creating a package, you can define parameters (with default values) that will be passed into every action/feed defined in the package: https://github.com/apache/incubator-openwhisk/blob/master/docs/packages.md#creating-a-package

This allows creation of reusable packages that users can bind to with their values for the parameters. An example of this might be a package with actions that interact with a database and the package level parameters would provide the database name, port, user name, and password.

I am adding this as a new issue rather than trying to expand the scope of #95

**Comment by jthomas** [comment]
Code to support this feature is complete with 9ce7ae6. This will also close #95

Remaining tasks before I can close this issue....

- [ ] Update main README.md
- [ ] Update package plugin README.md
- [ ] Send PRs to update Serverless Framework site with this information.

**Comment by jthomas** [comment]
Feature documented here: https://github.com/serverless/serverless-openwhisk#working-with-packages
