### ISSUE TITLE
Allow Binding To A Package and Supply Parameters

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless-openwhisk#97]
Packages can have parameters (see #96) that allow users to pass in common values to all actions/feeds defined within the package. To take advantage of this, users often have to create a binding to that package with the parameters that they want to send: https://github.com/apache/incubator-openwhisk/blob/master/docs/packages.md#creating-and-using-package-bindings

As noted in #96, this could allow someone to bind database credentials to a package that interacts with that database. The binding creates an instance of that package with the parameters defined. When the actions in a package are referenced through this binding, they receive the values defined by the binding.

**Comment by masodu** [comment]
If not considered, it would be desirable that the bindings should support both --param and --param-file: https://github.com/apache/incubator-openwhisk/blob/master/docs/parameters.md#working-with-parameter-files
