### ISSUE TITLE
Support Configuration for API Gateway

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless-openwhisk#98]
Per the docs here: https://serverless.com/framework/docs/providers/openwhisk/events/apigateway/ I do not see a way to manage API Gateway configuration: https://github.com/apache/incubator-openwhisk/blob/master/docs/apigateway.md#exporting-the-configuration

The configuration allows for a Swagger definition of the API that is hosted in the gateway. Additionally, for implementations such as IBM Cloud Functions (https://www.ibm.com/cloud/functions and https://console.bluemix.net/openwhisk/apimanagement) you are able to define authentication, rate limiting and CORS support - which they add into this configuration document.

I am not sure of the best way to bootstrap the configuration (outside of creating the API, making changes to its configuration and then exporting it) - but that could be a later step/issue.

**Comment by jthomas** [comment]
CORS support has now been added to the configuration. Changes made to support this will allow us to include other API GW configuration parameters in future. Will get more out in the next release...

**Comment by jthomas** [comment]
All options are now available in 0.17
